---
    provisioner:
      name: terraform
    
    verifier:
      name: terraform
      systems:
        - name: basic
          backend: local

    platforms:
      - name: terraform
    
    suites:
      - name: sample-jhub
        driver:
          name: terraform
          root_module_directory: examples/sample-jhub
          command_timeout: 12000
          parallelism: 1