prePuller:
  continuous:
    enabled: true
scheduling:
  userScheduler:
    enabled: true
  podPriority:
    enabled: true
  userPlaceholder:
    enabled: true
    replicas: 1
  userPods:
    nodeAffinity:
      matchNodePurpose: require
singleuser: 
  memory:
    limit: 1G
    guarantee: 512M
  cpu:
    limit: 1
    guarantee: 0.05
  image:
    name: gcr.io/jupyterhub-docker-images/jupyterhub-scipy
    tag: phys1600-spring2020
    pullPolicy: Always
  defaultUrl: "/lab"
  lifecycleHooks:
    postStart:
      exec:
        command: ["/bin/sh", "-c", "chmod -f 600 /home/jovyan/.ssh/id_rsa || true;"]
proxy:
  https:
    enabled: true
    type: secret
    secret:
      name: jupyterhub-tls
      key: tls.key
      crt: tls.crt

# proxy:
#   https:
#     enabled: true